# DEVELOPMENT

# Stage 1: Build the Angular app
FROM node:lts-alpine AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:dev

# Stage 2: Serve the app with Nginx
FROM nginx:alpine-slim

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/dist/front-end/browser /usr/share/nginx/html/front-end/browser

CMD ["nginx", "-g", "daemon off;"]